# Generated by Django 3.2 on 2023-02-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_rue', models.CharField(max_length=50)),
                ('Adresse', models.CharField(max_length=50)),
                ('Latitude', models.FloatField()),
                ('Langlitude', models.FloatField()),
            ],
        ),
    ]
